%YAML:1.0

verbosity: "INFO"

multi_threading_pubs: false
multi_threading_subs: false

use_fej: true
integration: "rk4"
use_stereo: false
max_cameras: 1

calib_cam_extrinsics: false
calib_cam_intrinsics: false
calib_cam_timeoffset: false
calib_imu_intrinsics: false
calib_imu_g_sensitivity: false

max_clones: 11
max_slam: 12
max_slam_in_update: 12
max_msckf_in_update: 15
dt_slam_delay: 2

gravity_mag: 9.8065

feat_rep_msckf: "GLOBAL_3D"
feat_rep_slam: "GLOBAL_3D"
feat_rep_aruco: "GLOBAL_3D"

try_zupt: false
zupt_chi2_multipler: 0
zupt_max_velocity: 0.1
zupt_noise_multiplier: 50
zupt_max_disparity: 1.5
zupt_only_at_beginning: true

init_window_time: 2.0
init_imu_thresh: 0.5
init_max_disparity: 4.0
init_max_features: 50

init_dyn_use: false
init_dyn_mle_opt_calib: false
init_dyn_mle_max_iter: 50
init_dyn_mle_max_time: 0.05
init_dyn_mle_max_threads: 4
init_dyn_num_pose: 6
init_dyn_min_deg: 10.0

init_dyn_inflation_ori: 10
init_dyn_inflation_vel: 100
init_dyn_inflation_bg: 10
init_dyn_inflation_ba: 100
init_dyn_min_rec_cond: 1e-12

init_dyn_bias_g: [0.0, 0.0, 0.0]
init_dyn_bias_a: [0.0, 0.0, 0.0]

record_timing_information: false
record_timing_filepath: "/tmp/openvins_drone_timing.txt"

save_total_state: false
filepath_est: "/tmp/openvins_drone_estimate.txt"
filepath_std: "/tmp/openvins_drone_estimate_std.txt"
filepath_gt: "/tmp/openvins_drone_groundtruth.txt"

use_klt: true
num_pts: 120
fast_threshold: 20
grid_x: 8
grid_y: 6
min_px_dist: 12
knn_ratio: 0.70
track_frequency: 15.0
downsample_cameras: false
num_opencv_threads: 1
histogram_method: "NONE"

use_aruco: false
num_aruco: 1024
downsize_aruco: true

up_msckf_sigma_px: 1
up_msckf_chi2_multipler: 1
up_slam_sigma_px: 1
up_slam_chi2_multipler: 1
up_aruco_sigma_px: 1
up_aruco_chi2_multipler: 1

use_mask: false

relative_config_imu: "kalibr_imu_chain.yaml"
relative_config_imucam: "kalibr_imucam_chain.yaml"
